### ISSUE TITLE
Allow a "minimal" cookiecutter output mode

### ISSUE THREAD

**Issue by zachmullen** [girder/cookiecutter-django-girder#44]
We could use this cookiecutter in two modes:

1. Teaching mode, that includes examples of best practices. Users would then need to delete the example code and add their own replacements. Useful for those doing this for the first time, or if they haven't done it in a while.
2. Minimal mode, where downstreams wouldn't need to delete any (or very much) code after they run the cookiecutter. This would be helpful for users that already know what they're doing.

**Comment by brianhelba** [comment]
Fixed by #111
